// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::Descriptor* Header_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Header_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Header_HmacHashFunction_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Field_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Field_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Field_ValueType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Message_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_message_2eproto() {
  protobuf_AddDesc_message_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "message.proto");
  GOOGLE_CHECK(file != NULL);
  Header_descriptor_ = file->message_type(0);
  static const int Header_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, message_length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, hmac_hash_function_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, hmac_signer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, hmac_key_version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, hmac_),
  };
  Header_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Header_descriptor_,
      Header::default_instance_,
      Header_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Header));
  Header_HmacHashFunction_descriptor_ = Header_descriptor_->enum_type(0);
  Field_descriptor_ = file->message_type(1);
  static const int Field_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, representation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_string_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_bytes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_integer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_double_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, value_bool_),
  };
  Field_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Field_descriptor_,
      Field::default_instance_,
      Field_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Field));
  Field_ValueType_descriptor_ = Field_descriptor_->enum_type(0);
  Message_descriptor_ = file->message_type(2);
  static const int Message_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, logger_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, severity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, env_version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, pid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, hostname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, fields_),
  };
  Message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Message_descriptor_,
      Message::default_instance_,
      Message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Message));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_message_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Header_descriptor_, &Header::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Field_descriptor_, &Field::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Message_descriptor_, &Message::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_message_2eproto() {
  delete Header::default_instance_;
  delete Header_reflection_;
  delete Field::default_instance_;
  delete Field_reflection_;
  delete Message::default_instance_;
  delete Message_reflection_;
}

void protobuf_AddDesc_message_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rmessage.proto\022\007message\"\307\001\n\006Header\022\026\n\016m"
    "essage_length\030\001 \002(\r\022A\n\022hmac_hash_functio"
    "n\030\003 \001(\0162 .message.Header.HmacHashFunctio"
    "n:\003MD5\022\023\n\013hmac_signer\030\004 \001(\t\022\030\n\020hmac_key_"
    "version\030\005 \001(\r\022\014\n\004hmac\030\006 \001(\014\"%\n\020HmacHashF"
    "unction\022\007\n\003MD5\020\000\022\010\n\004SHA1\020\001\"\242\002\n\005Field\022\014\n\004"
    "name\030\001 \002(\t\0224\n\nvalue_type\030\002 \001(\0162\030.message"
    ".Field.ValueType:\006STRING\022\026\n\016representati"
    "on\030\003 \001(\t\022\024\n\014value_string\030\004 \003(\t\022\023\n\013value_"
    "bytes\030\005 \003(\014\022\031\n\rvalue_integer\030\006 \003(\003B\002\020\001\022\030"
    "\n\014value_double\030\007 \003(\001B\002\020\001\022\026\n\nvalue_bool\030\010"
    " \003(\010B\002\020\001\"E\n\tValueType\022\n\n\006STRING\020\000\022\t\n\005BYT"
    "ES\020\001\022\013\n\007INTEGER\020\002\022\n\n\006DOUBLE\020\003\022\010\n\004BOOL\020\004\""
    "\302\001\n\007Message\022\014\n\004uuid\030\001 \002(\014\022\021\n\ttimestamp\030\002"
    " \002(\003\022\014\n\004type\030\003 \001(\t\022\016\n\006logger\030\004 \001(\t\022\023\n\010se"
    "verity\030\005 \001(\005:\0017\022\017\n\007payload\030\006 \001(\t\022\023\n\013env_"
    "version\030\007 \001(\t\022\013\n\003pid\030\010 \001(\005\022\020\n\010hostname\030\t"
    " \001(\t\022\036\n\006fields\030\n \003(\0132\016.message.Field", 716);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  Header::default_instance_ = new Header();
  Field::default_instance_ = new Field();
  Message::default_instance_ = new Message();
  Header::default_instance_->InitAsDefaultInstance();
  Field::default_instance_->InitAsDefaultInstance();
  Message::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_message_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_2eproto {
  StaticDescriptorInitializer_message_2eproto() {
    protobuf_AddDesc_message_2eproto();
  }
} static_descriptor_initializer_message_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* Header_HmacHashFunction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Header_HmacHashFunction_descriptor_;
}
bool Header_HmacHashFunction_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Header_HmacHashFunction Header::MD5;
const Header_HmacHashFunction Header::SHA1;
const Header_HmacHashFunction Header::HmacHashFunction_MIN;
const Header_HmacHashFunction Header::HmacHashFunction_MAX;
const int Header::HmacHashFunction_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Header::kMessageLengthFieldNumber;
const int Header::kHmacHashFunctionFieldNumber;
const int Header::kHmacSignerFieldNumber;
const int Header::kHmacKeyVersionFieldNumber;
const int Header::kHmacFieldNumber;
#endif  // !_MSC_VER

Header::Header()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.Header)
}

void Header::InitAsDefaultInstance() {
}

Header::Header(const Header& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.Header)
}

void Header::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  message_length_ = 0u;
  hmac_hash_function_ = 0;
  hmac_signer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hmac_key_version_ = 0u;
  hmac_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:message.Header)
  SharedDtor();
}

void Header::SharedDtor() {
  if (hmac_signer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hmac_signer_;
  }
  if (hmac_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hmac_;
  }
  if (this != default_instance_) {
  }
}

void Header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Header::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Header_descriptor_;
}

const Header& Header::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

Header* Header::default_instance_ = NULL;

Header* Header::New() const {
  return new Header;
}

void Header::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Header*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(message_length_, hmac_hash_function_);
    if (has_hmac_signer()) {
      if (hmac_signer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        hmac_signer_->clear();
      }
    }
    hmac_key_version_ = 0u;
    if (has_hmac()) {
      if (hmac_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        hmac_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.Header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 message_length = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &message_length_)));
          set_has_message_length();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_hmac_hash_function;
        break;
      }

      // optional .message.Header.HmacHashFunction hmac_hash_function = 3 [default = MD5];
      case 3: {
        if (tag == 24) {
         parse_hmac_hash_function:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::message::Header_HmacHashFunction_IsValid(value)) {
            set_hmac_hash_function(static_cast< ::message::Header_HmacHashFunction >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_hmac_signer;
        break;
      }

      // optional string hmac_signer = 4;
      case 4: {
        if (tag == 34) {
         parse_hmac_signer:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hmac_signer()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->hmac_signer().data(), this->hmac_signer().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hmac_signer");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_hmac_key_version;
        break;
      }

      // optional uint32 hmac_key_version = 5;
      case 5: {
        if (tag == 40) {
         parse_hmac_key_version:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hmac_key_version_)));
          set_has_hmac_key_version();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_hmac;
        break;
      }

      // optional bytes hmac = 6;
      case 6: {
        if (tag == 50) {
         parse_hmac:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hmac()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.Header)
  return false;
#undef DO_
}

void Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.Header)
  // required uint32 message_length = 1;
  if (has_message_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->message_length(), output);
  }

  // optional .message.Header.HmacHashFunction hmac_hash_function = 3 [default = MD5];
  if (has_hmac_hash_function()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->hmac_hash_function(), output);
  }

  // optional string hmac_signer = 4;
  if (has_hmac_signer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hmac_signer().data(), this->hmac_signer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hmac_signer");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->hmac_signer(), output);
  }

  // optional uint32 hmac_key_version = 5;
  if (has_hmac_key_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->hmac_key_version(), output);
  }

  // optional bytes hmac = 6;
  if (has_hmac()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->hmac(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.Header)
}

::google::protobuf::uint8* Header::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.Header)
  // required uint32 message_length = 1;
  if (has_message_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->message_length(), target);
  }

  // optional .message.Header.HmacHashFunction hmac_hash_function = 3 [default = MD5];
  if (has_hmac_hash_function()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->hmac_hash_function(), target);
  }

  // optional string hmac_signer = 4;
  if (has_hmac_signer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hmac_signer().data(), this->hmac_signer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hmac_signer");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->hmac_signer(), target);
  }

  // optional uint32 hmac_key_version = 5;
  if (has_hmac_key_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->hmac_key_version(), target);
  }

  // optional bytes hmac = 6;
  if (has_hmac()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->hmac(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.Header)
  return target;
}

int Header::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 message_length = 1;
    if (has_message_length()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->message_length());
    }

    // optional .message.Header.HmacHashFunction hmac_hash_function = 3 [default = MD5];
    if (has_hmac_hash_function()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->hmac_hash_function());
    }

    // optional string hmac_signer = 4;
    if (has_hmac_signer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->hmac_signer());
    }

    // optional uint32 hmac_key_version = 5;
    if (has_hmac_key_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->hmac_key_version());
    }

    // optional bytes hmac = 6;
    if (has_hmac()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->hmac());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Header::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Header* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Header*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Header::MergeFrom(const Header& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message_length()) {
      set_message_length(from.message_length());
    }
    if (from.has_hmac_hash_function()) {
      set_hmac_hash_function(from.hmac_hash_function());
    }
    if (from.has_hmac_signer()) {
      set_hmac_signer(from.hmac_signer());
    }
    if (from.has_hmac_key_version()) {
      set_hmac_key_version(from.hmac_key_version());
    }
    if (from.has_hmac()) {
      set_hmac(from.hmac());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Header::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Header::CopyFrom(const Header& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Header::Swap(Header* other) {
  if (other != this) {
    std::swap(message_length_, other->message_length_);
    std::swap(hmac_hash_function_, other->hmac_hash_function_);
    std::swap(hmac_signer_, other->hmac_signer_);
    std::swap(hmac_key_version_, other->hmac_key_version_);
    std::swap(hmac_, other->hmac_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Header::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Header_descriptor_;
  metadata.reflection = Header_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* Field_ValueType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Field_ValueType_descriptor_;
}
bool Field_ValueType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Field_ValueType Field::STRING;
const Field_ValueType Field::BYTES;
const Field_ValueType Field::INTEGER;
const Field_ValueType Field::DOUBLE;
const Field_ValueType Field::BOOL;
const Field_ValueType Field::ValueType_MIN;
const Field_ValueType Field::ValueType_MAX;
const int Field::ValueType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Field::kNameFieldNumber;
const int Field::kValueTypeFieldNumber;
const int Field::kRepresentationFieldNumber;
const int Field::kValueStringFieldNumber;
const int Field::kValueBytesFieldNumber;
const int Field::kValueIntegerFieldNumber;
const int Field::kValueDoubleFieldNumber;
const int Field::kValueBoolFieldNumber;
#endif  // !_MSC_VER

Field::Field()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.Field)
}

void Field::InitAsDefaultInstance() {
}

Field::Field(const Field& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.Field)
}

void Field::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_type_ = 0;
  representation_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Field::~Field() {
  // @@protoc_insertion_point(destructor:message.Field)
  SharedDtor();
}

void Field::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (representation_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete representation_;
  }
  if (this != default_instance_) {
  }
}

void Field::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Field::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Field_descriptor_;
}

const Field& Field::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

Field* Field::default_instance_ = NULL;

Field* Field::New() const {
  return new Field;
}

void Field::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    value_type_ = 0;
    if (has_representation()) {
      if (representation_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        representation_->clear();
      }
    }
  }
  value_string_.Clear();
  value_bytes_.Clear();
  value_integer_.Clear();
  value_double_.Clear();
  value_bool_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Field::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.Field)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_value_type;
        break;
      }

      // optional .message.Field.ValueType value_type = 2 [default = STRING];
      case 2: {
        if (tag == 16) {
         parse_value_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::message::Field_ValueType_IsValid(value)) {
            set_value_type(static_cast< ::message::Field_ValueType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_representation;
        break;
      }

      // optional string representation = 3;
      case 3: {
        if (tag == 26) {
         parse_representation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_representation()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->representation().data(), this->representation().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "representation");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_value_string;
        break;
      }

      // repeated string value_string = 4;
      case 4: {
        if (tag == 34) {
         parse_value_string:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value_string()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value_string(this->value_string_size() - 1).data(),
            this->value_string(this->value_string_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "value_string");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_value_string;
        if (input->ExpectTag(42)) goto parse_value_bytes;
        break;
      }

      // repeated bytes value_bytes = 5;
      case 5: {
        if (tag == 42) {
         parse_value_bytes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_value_bytes()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_value_bytes;
        if (input->ExpectTag(50)) goto parse_value_integer;
        break;
      }

      // repeated int64 value_integer = 6 [packed = true];
      case 6: {
        if (tag == 50) {
         parse_value_integer:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_value_integer())));
        } else if (tag == 48) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 50, input, this->mutable_value_integer())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_value_double;
        break;
      }

      // repeated double value_double = 7 [packed = true];
      case 7: {
        if (tag == 58) {
         parse_value_double:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_value_double())));
        } else if (tag == 57) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 58, input, this->mutable_value_double())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_value_bool;
        break;
      }

      // repeated bool value_bool = 8 [packed = true];
      case 8: {
        if (tag == 66) {
         parse_value_bool:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_value_bool())));
        } else if (tag == 64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 66, input, this->mutable_value_bool())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.Field)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.Field)
  return false;
#undef DO_
}

void Field::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.Field)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional .message.Field.ValueType value_type = 2 [default = STRING];
  if (has_value_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->value_type(), output);
  }

  // optional string representation = 3;
  if (has_representation()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->representation().data(), this->representation().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "representation");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->representation(), output);
  }

  // repeated string value_string = 4;
  for (int i = 0; i < this->value_string_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->value_string(i).data(), this->value_string(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "value_string");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->value_string(i), output);
  }

  // repeated bytes value_bytes = 5;
  for (int i = 0; i < this->value_bytes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      5, this->value_bytes(i), output);
  }

  // repeated int64 value_integer = 6 [packed = true];
  if (this->value_integer_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_integer_cached_byte_size_);
  }
  for (int i = 0; i < this->value_integer_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64NoTag(
      this->value_integer(i), output);
  }

  // repeated double value_double = 7 [packed = true];
  if (this->value_double_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(7, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_double_cached_byte_size_);
  }
  for (int i = 0; i < this->value_double_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->value_double(i), output);
  }

  // repeated bool value_bool = 8 [packed = true];
  if (this->value_bool_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(8, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_bool_cached_byte_size_);
  }
  for (int i = 0; i < this->value_bool_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBoolNoTag(
      this->value_bool(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.Field)
}

::google::protobuf::uint8* Field::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.Field)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional .message.Field.ValueType value_type = 2 [default = STRING];
  if (has_value_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->value_type(), target);
  }

  // optional string representation = 3;
  if (has_representation()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->representation().data(), this->representation().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "representation");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->representation(), target);
  }

  // repeated string value_string = 4;
  for (int i = 0; i < this->value_string_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value_string(i).data(), this->value_string(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "value_string");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->value_string(i), target);
  }

  // repeated bytes value_bytes = 5;
  for (int i = 0; i < this->value_bytes_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(5, this->value_bytes(i), target);
  }

  // repeated int64 value_integer = 6 [packed = true];
  if (this->value_integer_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _value_integer_cached_byte_size_, target);
  }
  for (int i = 0; i < this->value_integer_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64NoTagToArray(this->value_integer(i), target);
  }

  // repeated double value_double = 7 [packed = true];
  if (this->value_double_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      7,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _value_double_cached_byte_size_, target);
  }
  for (int i = 0; i < this->value_double_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->value_double(i), target);
  }

  // repeated bool value_bool = 8 [packed = true];
  if (this->value_bool_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      8,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _value_bool_cached_byte_size_, target);
  }
  for (int i = 0; i < this->value_bool_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolNoTagToArray(this->value_bool(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.Field)
  return target;
}

int Field::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional .message.Field.ValueType value_type = 2 [default = STRING];
    if (has_value_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->value_type());
    }

    // optional string representation = 3;
    if (has_representation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->representation());
    }

  }
  // repeated string value_string = 4;
  total_size += 1 * this->value_string_size();
  for (int i = 0; i < this->value_string_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value_string(i));
  }

  // repeated bytes value_bytes = 5;
  total_size += 1 * this->value_bytes_size();
  for (int i = 0; i < this->value_bytes_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->value_bytes(i));
  }

  // repeated int64 value_integer = 6 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->value_integer_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int64Size(this->value_integer(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_integer_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated double value_double = 7 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->value_double_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_double_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated bool value_bool = 8 [packed = true];
  {
    int data_size = 0;
    data_size = 1 * this->value_bool_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_bool_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Field::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Field* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Field*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Field::MergeFrom(const Field& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_string_.MergeFrom(from.value_string_);
  value_bytes_.MergeFrom(from.value_bytes_);
  value_integer_.MergeFrom(from.value_integer_);
  value_double_.MergeFrom(from.value_double_);
  value_bool_.MergeFrom(from.value_bool_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_value_type()) {
      set_value_type(from.value_type());
    }
    if (from.has_representation()) {
      set_representation(from.representation());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Field::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Field::CopyFrom(const Field& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Field::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Field::Swap(Field* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(value_type_, other->value_type_);
    std::swap(representation_, other->representation_);
    value_string_.Swap(&other->value_string_);
    value_bytes_.Swap(&other->value_bytes_);
    value_integer_.Swap(&other->value_integer_);
    value_double_.Swap(&other->value_double_);
    value_bool_.Swap(&other->value_bool_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Field::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Field_descriptor_;
  metadata.reflection = Field_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Message::kUuidFieldNumber;
const int Message::kTimestampFieldNumber;
const int Message::kTypeFieldNumber;
const int Message::kLoggerFieldNumber;
const int Message::kSeverityFieldNumber;
const int Message::kPayloadFieldNumber;
const int Message::kEnvVersionFieldNumber;
const int Message::kPidFieldNumber;
const int Message::kHostnameFieldNumber;
const int Message::kFieldsFieldNumber;
#endif  // !_MSC_VER

Message::Message()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.Message)
}

void Message::InitAsDefaultInstance() {
}

Message::Message(const Message& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.Message)
}

void Message::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  timestamp_ = GOOGLE_LONGLONG(0);
  type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logger_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  severity_ = 7;
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  env_version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pid_ = 0;
  hostname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:message.Message)
  SharedDtor();
}

void Message::SharedDtor() {
  if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uuid_;
  }
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (logger_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete logger_;
  }
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete payload_;
  }
  if (env_version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete env_version_;
  }
  if (hostname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hostname_;
  }
  if (this != default_instance_) {
  }
}

void Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Message_descriptor_;
}

const Message& Message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

Message* Message::default_instance_ = NULL;

Message* Message::New() const {
  return new Message;
}

void Message::Clear() {
  if (_has_bits_[0 / 32] & 255) {
    if (has_uuid()) {
      if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        uuid_->clear();
      }
    }
    timestamp_ = GOOGLE_LONGLONG(0);
    if (has_type()) {
      if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        type_->clear();
      }
    }
    if (has_logger()) {
      if (logger_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        logger_->clear();
      }
    }
    severity_ = 7;
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        payload_->clear();
      }
    }
    if (has_env_version()) {
      if (env_version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        env_version_->clear();
      }
    }
    pid_ = 0;
  }
  if (has_hostname()) {
    if (hostname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      hostname_->clear();
    }
  }
  fields_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.Message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes uuid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_uuid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // required int64 timestamp = 2;
      case 2: {
        if (tag == 16) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_type;
        break;
      }

      // optional string type = 3;
      case 3: {
        if (tag == 26) {
         parse_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_logger;
        break;
      }

      // optional string logger = 4;
      case 4: {
        if (tag == 34) {
         parse_logger:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_logger()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->logger().data(), this->logger().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "logger");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_severity;
        break;
      }

      // optional int32 severity = 5 [default = 7];
      case 5: {
        if (tag == 40) {
         parse_severity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &severity_)));
          set_has_severity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_payload;
        break;
      }

      // optional string payload = 6;
      case 6: {
        if (tag == 50) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->payload().data(), this->payload().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "payload");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_env_version;
        break;
      }

      // optional string env_version = 7;
      case 7: {
        if (tag == 58) {
         parse_env_version:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_env_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->env_version().data(), this->env_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "env_version");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_pid;
        break;
      }

      // optional int32 pid = 8;
      case 8: {
        if (tag == 64) {
         parse_pid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pid_)));
          set_has_pid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_hostname;
        break;
      }

      // optional string hostname = 9;
      case 9: {
        if (tag == 74) {
         parse_hostname:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->hostname().data(), this->hostname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hostname");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_fields;
        break;
      }

      // repeated .message.Field fields = 10;
      case 10: {
        if (tag == 82) {
         parse_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_fields()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_fields;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.Message)
  return false;
#undef DO_
}

void Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.Message)
  // required bytes uuid = 1;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->uuid(), output);
  }

  // required int64 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->timestamp(), output);
  }

  // optional string type = 3;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->type(), output);
  }

  // optional string logger = 4;
  if (has_logger()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->logger().data(), this->logger().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "logger");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->logger(), output);
  }

  // optional int32 severity = 5 [default = 7];
  if (has_severity()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->severity(), output);
  }

  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "payload");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->payload(), output);
  }

  // optional string env_version = 7;
  if (has_env_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->env_version().data(), this->env_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "env_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->env_version(), output);
  }

  // optional int32 pid = 8;
  if (has_pid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->pid(), output);
  }

  // optional string hostname = 9;
  if (has_hostname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostname().data(), this->hostname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hostname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->hostname(), output);
  }

  // repeated .message.Field fields = 10;
  for (int i = 0; i < this->fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->fields(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.Message)
}

::google::protobuf::uint8* Message::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.Message)
  // required bytes uuid = 1;
  if (has_uuid()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->uuid(), target);
  }

  // required int64 timestamp = 2;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->timestamp(), target);
  }

  // optional string type = 3;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->type(), target);
  }

  // optional string logger = 4;
  if (has_logger()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->logger().data(), this->logger().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "logger");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->logger(), target);
  }

  // optional int32 severity = 5 [default = 7];
  if (has_severity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->severity(), target);
  }

  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "payload");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->payload(), target);
  }

  // optional string env_version = 7;
  if (has_env_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->env_version().data(), this->env_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "env_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->env_version(), target);
  }

  // optional int32 pid = 8;
  if (has_pid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->pid(), target);
  }

  // optional string hostname = 9;
  if (has_hostname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostname().data(), this->hostname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hostname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->hostname(), target);
  }

  // repeated .message.Field fields = 10;
  for (int i = 0; i < this->fields_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->fields(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.Message)
  return target;
}

int Message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes uuid = 1;
    if (has_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->uuid());
    }

    // required int64 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->timestamp());
    }

    // optional string type = 3;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type());
    }

    // optional string logger = 4;
    if (has_logger()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->logger());
    }

    // optional int32 severity = 5 [default = 7];
    if (has_severity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->severity());
    }

    // optional string payload = 6;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->payload());
    }

    // optional string env_version = 7;
    if (has_env_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->env_version());
    }

    // optional int32 pid = 8;
    if (has_pid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pid());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string hostname = 9;
    if (has_hostname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->hostname());
    }

  }
  // repeated .message.Field fields = 10;
  total_size += 1 * this->fields_size();
  for (int i = 0; i < this->fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->fields(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Message::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Message* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Message*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Message::MergeFrom(const Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  fields_.MergeFrom(from.fields_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uuid()) {
      set_uuid(from.uuid());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_logger()) {
      set_logger(from.logger());
    }
    if (from.has_severity()) {
      set_severity(from.severity());
    }
    if (from.has_payload()) {
      set_payload(from.payload());
    }
    if (from.has_env_version()) {
      set_env_version(from.env_version());
    }
    if (from.has_pid()) {
      set_pid(from.pid());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_hostname()) {
      set_hostname(from.hostname());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Message::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message::CopyFrom(const Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->fields())) return false;
  return true;
}

void Message::Swap(Message* other) {
  if (other != this) {
    std::swap(uuid_, other->uuid_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(type_, other->type_);
    std::swap(logger_, other->logger_);
    std::swap(severity_, other->severity_);
    std::swap(payload_, other->payload_);
    std::swap(env_version_, other->env_version_);
    std::swap(pid_, other->pid_);
    std::swap(hostname_, other->hostname_);
    fields_.Swap(&other->fields_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Message_descriptor_;
  metadata.reflection = Message_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
